name: Draft release
on:
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        required: true
jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: rm .gitignore
      - name: git commit
        run: |
          git config user.name github-actions[bot]
          git config user.email actions@github.com
          git add -A
          git commit -m '${{ inputs.tag-name }}'
      - run: git tag ${{ inputs.tag-name }}
      - run: git push origin ${{ inputs.tag-name }}
      - run: gh release create ${{ inputs.tag-name }} -d
        env:
          GH_TOKEN: ${{ github.token }}
